// ============================================================
// Model Name Extractor & Generator
// Ozon requires "Название модели" (attribute 9048) for electronics
// ============================================================

import { logger } from "@onzo/logger";
import { deepseekComplete } from "../langgraph/client/deepseek-client.js";

const MAX_LENGTH = parseInt(process.env.MODEL_NAME_MAX_LENGTH || "60", 10);
const FALLBACK_TEMPLATE = process.env.MODEL_NAME_RELAX_TEMPLATE || "Model-{title}";

/**
 * Extract model name from product data.
 * Priority: SKU model field > specs > title keywords
 */
export function extractModelName(product: {
  title: string;
  specs?: Array<{ name: string; value: string }>;
  sku?: string;
}): string | null {
  // Try specs: look for "型号", "model", "款式" fields
  if (product.specs) {
    for (const spec of product.specs) {
      const name = spec.name.toLowerCase();
      if (name.includes("型号") || name.includes("model") || name.includes("款式") || name.includes("规格")) {
        const val = spec.value?.trim();
        if (val && val.length >= 2 && val.length <= MAX_LENGTH) return val;
      }
    }
  }

  // Try SKU: extract model-like pattern (alphanumeric codes)
  if (product.sku) {
    const modelMatch = product.sku.match(/[A-Z0-9]{3,}[-\s]?[A-Z0-9]{0,}/);
    if (modelMatch) return modelMatch[0].slice(0, MAX_LENGTH);
  }

  return null;
}

/**
 * Generate model name via DeepSeek LLM.
 * Input: product title, specs, category.
 * Output: Ozon-compliant short model name.
 */
export async function generateModelName(product: {
  title: string;
  category?: string;
  specs?: Array<{ name: string; value: string }>;
}): Promise<string> {
  try {
    const specsStr = (product.specs || []).map(s => `${s.name}:${s.value}`).join(", ");
    const prompt = `商品信息: "${product.title}". 规格: ${specsStr}. 类目: ${product.category || "电子产品"}`;

    const result = await deepseekComplete(
      "你是Ozon商品上架专家。生成一个简洁的商品型号名称（Название модели），用于合并商品卡片。要求：15-40个字符，包含品牌/型号关键词，便于搜索归类。只返回型号名称，不要解释。",
      prompt,
    );
    const model = result.trim().replace(/["']/g, "").slice(0, MAX_LENGTH);
    if (model && model.length >= 3) return model;
  } catch (err) {
    logger.warn({ err: (err as Error).message }, "Model name LLM generation failed, using template");
  }

  // Fallback: use template
  return fallbackModelName(product.title);
}

/**
 * Template-based fallback when LLM unavailable.
 */
export function fallbackModelName(title: string): string {
  const cleanTitle = title.replace(/[^\w一-鿿\s-]/g, "").replace(/\s+/g, "-");
  return FALLBACK_TEMPLATE.replace("{title}", cleanTitle).slice(0, MAX_LENGTH);
}

/**
 * Get or generate model name for a product.
 * Returns the model name and whether it was auto-generated.
 */
export async function resolveModelName(product: {
  title: string;
  specs?: Array<{ name: string; value: string }>;
  sku?: string;
  category?: string;
}): Promise<{ modelName: string; autoGenerated: boolean }> {
  // 1. Try extraction
  const extracted = extractModelName(product);
  if (extracted) {
    logger.info({ modelName: extracted, source: "extracted" }, "Model name resolved");
    return { modelName: extracted, autoGenerated: false };
  }

  // 2. Try LLM generation
  logger.info({ title: product.title }, "Model name not found, generating via LLM");
  const generated = await generateModelName(product);
  return { modelName: generated, autoGenerated: true };
}
